# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142mu6DCErdx_frql6Wvx2OtoFU6kGze3
"""

!apt-get install ghostscript

from tkinter import *

!pip install "camelot-py[cv]" -q

import camelot

import pandas as pd

filePath = input("Enter the PDF file: ")
# filePath = "/content/samplereport.pdf"
tables = camelot.read_pdf(filePath, pages='all', flavor='stream')

for table in tables:
  if table.parsing_report.get('accuracy') == 0:
    tables.remove(table)

output_excel_file = input("Enter an excel file to export tables : ")
tables.export(output_excel_file, f="excel")